treewide: Introduce release multi variant into one tag
and some adjustments and fixes

Co-authored-by: Chise <lqff.yt@gmail.com>
Signed-off-by: hazepynut <naden.hey@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,49 +3,104 @@ name: Release Build
 on:
   workflow_dispatch:
 
-env:
-  STATUS: STABLE
-  CHAT_ID: ${{ secrets.CHAT_ID }}
-  TOKEN: ${{ secrets.TOKEN }}
-  GH_TOKEN: ${{ secrets.GH_TOKEN }}
-  BUILD_KERNEL: "true"
-
 jobs:
-  non-ksu:
-    name: Build Non-KSU
+  build:
+    strategy:
+      matrix:
+        variant:
+          - { name: "Non-KSU", KernelSU: "None", SUSFS4KSU: "false", KSU_MANUAL_HOOK: "false", LAST_BUILD: "false" }
+          - { name: "KSUxSuSFS", KernelSU: "Official", SUSFS4KSU: "true", KSU_MANUAL_HOOK: "false", LAST_BUILD: "false" }
+          - { name: "KSU-Next with SuSFS", KernelSU: "Next", SUSFS4KSU: "true", KSU_MANUAL_HOOK: "true", LAST_BUILD: "true" }
+    name: Build ${{ matrix.variant.name }}
     uses: ./.github/workflows/build.yml
     secrets: inherit
     with:
-      KernelSU: None
-      SUSFS4KSU: "false"
+      KernelSU: ${{ matrix.variant.KernelSU }}
+      SUSFS4KSU: ${{ matrix.variant.SUSFS4KSU }}
       Clang: Default
       BUILD_BOOTIMG: "true"
-      UPLOAD2GH: "true"
       BUILD_LKMS: "false"
-      KSU_MANUAL_HOOK: "false"
+      KSU_MANUAL_HOOK: ${{ matrix.variant.KSU_MANUAL_HOOK }}
+      LAST_BUILD: ${{ matrix.variant.LAST_BUILD }}
 
-  ksuxsusfs:
-    name: Build KSUxSuSFS
-    uses: ./.github/workflows/build.yml
-    secrets: inherit
-    with:
-      KernelSU: Official KernelSU
-      SUSFS4KSU: "true"
-      Clang: Default
-      BUILD_BOOTIMG: "true"
-      UPLOAD2GH: "true"
-      BUILD_LKMS: "false"
-      KSU_MANUAL_HOOK: "false"
+  release:
+    name: Create Unified Release
+    needs: build  # Waits for all build jobs to be complete
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout current repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
 
-  ksunxsusfs:
-    name: Build KSU-Next with SuSFS
-    uses: ./.github/workflows/build.yml
-    secrets: inherit
-    with:
-      KernelSU: KernelSU-Next
-      SUSFS4KSU: "true"
-      Clang: Default
-      BUILD_BOOTIMG: "true"
-      UPLOAD2GH: "true"
-      BUILD_LKMS: "false"
-      KSU_MANUAL_HOOK: "true"
+      - name: Download All Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: release_files
+
+      - name: List Downloaded Files
+        run: ls -R release_files
+
+      - name: Extract variables from info.txt
+        run: |
+          set -e  # Exit on error
+          info_file="release_files/info-${{ github.run_number }}/info.txt"
+          if [[ -f "$info_file" ]]; then
+            while IFS='=' read -r key value; do
+              key=$(echo -n "$key" | tr -d ' ')
+              value=$(echo -n "$value" | tr -d ' ')
+              echo "$key=$value" # for debugging
+              echo "$key=$value" >> $GITHUB_ENV
+            done < "$info_file"
+            rm -f "$info_file"
+          else
+            echo "error: info.txt not found!"
+            exit 1
+          fi
+
+      # Get the Latest Tag from GitHub
+      - name: Generate and create new tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+            # Fetch latest tag from release repo
+            TAG="$(gh api repos/$REL_REPO/tags --jq '.[0].name')"
+            [ -z "$TAG" ] && TAG="$KERNEL_NAME-r0"
+
+            RELEASE_TAG="$(echo "$TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')"
+
+            echo "Release tag: $RELEASE_TAG"
+            echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
+
+      - name: Upload All Builds to GKI Release Repo
+        uses: softprops/action-gh-release@v2
+        with:
+          repository: ${{ env.REL_REPO }}
+          name: ${{ env.RELEASE_NAME }}
+          tag_name: ${{ env.RELEASE_TAG }}
+          prerelease: true
+          files: release_files/**/*
+          body: |
+            ### 📢 QuartiX GKI Release
+            -> Linux Version ${{ env.KVER }}
+            -> KSU Next ${{ env.KSU_NEXT_VER }}
+            -> Official KernelSU ${{ env.KSU_OFC_VER }}
+            -> SUSFS ඞ ${{ env.SUSFS_VER }}
+
+            #### Build Details
+            [GKI Builder](${{ env.BUILDER_REPO }})
+            -> Last Commit: [here](${{ env.BUILDER_LAST_COMMIT }})
+            -> Branch: ${{ env.BUILDER_CUR_BRANCH }}
+
+            [Kernel Source](${{ env.KERNEL_REPO }})
+            -> Last Commit: [here](${{ env.KERNEL_LAST_COMMIT }})
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+      - name: Send notification to TG
+        run: |
+          source ./functions.sh
+          send_msg "📦 Release complete! [GitHub](https://github.com/${{ env.REL_REPO }}/releases/tag/${{ env.RELEASE_TAG }})"
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+          CHAT_ID: ${{ secrets.CHAT_ID }}
